/////////////////////////////////////////////////////////////////////////
//
// 'ORGANIZATION AND SIMULTANEOUS FITS' RooFit tutorial macro #503
// 
// Reading and using a workspace
//
// --> The input file for this macro is generated by rf502_wspaceread.C
// 
//
// 07/2008 - Wouter Verkerke 
//
/////////////////////////////////////////////////////////////////////////
/*
 #ifndef __CINT__
 #include "RooGlobalFunc.h"
 #endif
 #include "RooRealVar.h"
 #include "RooDataSet.h"
 #include "RooGaussian.h"
 #include "RooConstVar.h"
 #include "RooChebychev.h"
 #include "RooAddPdf.h"
 #include "RooWorkspace.h"
 #include "RooPlot.h"
 #include "TCanvas.h"
 #include "TAxis.h"
 #include "TFile.h"
 #include "TH1.h"
 */
using namespace RooFit ;

void backgroundFits_qqzz_1Dw(string fileName = "../../Histogramming/rootFiles_mZ12/ZZ_2e2mu.root", int channel = 3)
{
	
	gSystem->AddIncludePath("-I$ROOFITSYS/include");
	gROOT->ProcessLine(".L ../CreateDatacards/include/tdrstyle.C");
	setTDRStyle();
	gStyle->SetPadLeftMargin(0.16);

	string schannel;
	if (channel == 1) schannel = "4mu";
	else if (channel == 2) schannel = "4e";
	else if (channel == 3) schannel = "2mu2e";
	else std::cout << "Not a valid channel" << std::endl;
	
	// R e a d   w o r k s p a c e   f r o m   f i l e
	// -----------------------------------------------
	
	// Open input file with workspace (generated by rf14_wspacewrite)
	char infile[192];
	sprintf(infile,"%s",fileName.c_str());
	TFile *f = new TFile(infile) ;
	char outfile[192];
	sprintf( outfile, "figs/pdf_%s_bkg.eps", schannel.c_str() );
	//f->ls();
	//RooRealVar CMS_zz4l_mass("ZZMass","ZZMass",110.,250.);
	//RooRealVar mZStar("mZStar","m'_{Z*}",10,90);
	//TCut cutString2 = "mZStar > 12";
	//RooDataSet dataT("dataT","dataT",(TTree*)f->Get("outTree"),RooArgSet(CMS_zz4l_mass,mZStar),cutString2);
	//RooDataSet set("set","set",(TTree*)f->Get("outTree"),RooArgSet(CMS_zz4l_mass));
	//RooDataSet data("data","data",(TTree*)file->Get("outTree"),mZStar);
	//RooDataSet* set = (RooDataSet*) dataT.reduce(RooArgSet(CMS_zz4l_mass)) ; 
	RooRealVar* MC_weight = new RooRealVar("scaleWeight","scaleWeight",0.,2.) ; 
	RooRealVar* ZZMass = new RooRealVar("mass4l","mass4l",100.,1000.);
	RooDataSet* set = new RooDataSet("set","set",(TTree*)f->Get("Ana/passedEvents"),RooArgSet(*ZZMass,*MC_weight),0,"scaleWeight");

	double totalweight = 0.;
	double totalweight_z = 0.;
	for (int i=0 ; i<set->numEntries() ; i++) { 
	  //set->get(i) ; 
	  RooArgSet* row = set->get(i) ;
	  //row->Print("v");
	  totalweight += set->weight();
	  if (row->getRealValue("mass4l") < 200) totalweight_z += set->weight();
	  //cout << row->getRealValue("mass4l") << " = " << set->weight() << endl ; 
	} 
	std::cout << "nEntries: " << set->numEntries() << ", totalweight: " << totalweight << ", totalweight_z: " << totalweight_z << std::endl;

	
	gSystem->Load("../CreateDatacards/PDFs/HZZ4LRooPdfs_cc.so");
	
	//// ---------------------------------------
	//Background
	RooRealVar CMS_qqzzbkg_a0("CMS_qqzzbkg_a0","CMS_qqzzbkg_a0",115.3,0.,200.);
	RooRealVar CMS_qqzzbkg_a1("CMS_qqzzbkg_a1","CMS_qqzzbkg_a1",21.96,0.,200.);
	RooRealVar CMS_qqzzbkg_a2("CMS_qqzzbkg_a2","CMS_qqzzbkg_a2",122.8,0.,200.);
	RooRealVar CMS_qqzzbkg_a3("CMS_qqzzbkg_a3","CMS_qqzzbkg_a3",0.03479,0.,1.);
	RooRealVar CMS_qqzzbkg_a4("CMS_qqzzbkg_a4","CMS_qqzzbkg_a4",185.5,0.,200.);
	RooRealVar CMS_qqzzbkg_a5("CMS_qqzzbkg_a5","CMS_qqzzbkg_a5",12.67,0.,200.);
	RooRealVar CMS_qqzzbkg_a6("CMS_qqzzbkg_a6","CMS_qqzzbkg_a6",34.81,0.,100.);
	RooRealVar CMS_qqzzbkg_a7("CMS_qqzzbkg_a7","CMS_qqzzbkg_a7",0.1393,0.,1.);
	RooRealVar CMS_qqzzbkg_a8("CMS_qqzzbkg_a8","CMS_qqzzbkg_a8",66.,0.,200.);
	RooRealVar CMS_qqzzbkg_a9("CMS_qqzzbkg_a9","CMS_qqzzbkg_a9",0.07191,0.,1.);
	RooRealVar CMS_qqzzbkg_a10("CMS_qqzzbkg_a10","CMS_qqzzbkg_a10",94.11,0.,200.);
	RooRealVar CMS_qqzzbkg_a11("CMS_qqzzbkg_a11","CMS_qqzzbkg_a11",-5.111,-100.,100.);
	RooRealVar CMS_qqzzbkg_a12("CMS_qqzzbkg_a12","CMS_qqzzbkg_a12",4834,0.,10000.);
	RooRealVar CMS_qqzzbkg_a13("CMS_qqzzbkg_a13","CMS_qqzzbkg_a13",0.2543,0.,1.);
	
    if (channel == 1){
      ///* 4mu
	CMS_qqzzbkg_a0.setVal(103.622);
	CMS_qqzzbkg_a1.setVal(9.29059);
	CMS_qqzzbkg_a2.setVal(119.039);
	CMS_qqzzbkg_a3.setVal(0.0436862);
	CMS_qqzzbkg_a4.setVal(184.985);
	CMS_qqzzbkg_a5.setVal(8.70755);
	CMS_qqzzbkg_a6.setVal(39.0814);
	CMS_qqzzbkg_a7.setVal(0.103346);
	CMS_qqzzbkg_a8.setVal(51.2894);
	CMS_qqzzbkg_a9.setVal(0.0420401);
	CMS_qqzzbkg_a10.setVal(98.6157);
	CMS_qqzzbkg_a11.setVal(-6.74448);
	CMS_qqzzbkg_a12.setVal(4928.01);
	CMS_qqzzbkg_a13.setVal(0.0773975);
	//*/
    }
    else if (channel == 2){
      ///* 4e
	CMS_qqzzbkg_a0.setVal(110.703);
	CMS_qqzzbkg_a1.setVal(17.9813);
	CMS_qqzzbkg_a2.setVal(123.261);
	CMS_qqzzbkg_a3.setVal(0.0417385);
	CMS_qqzzbkg_a4.setVal(184.812);
	CMS_qqzzbkg_a5.setVal(11.5634);
	CMS_qqzzbkg_a6.setVal(33.6581);
	CMS_qqzzbkg_a7.setVal(0.128189);
	CMS_qqzzbkg_a8.setVal(58.9151);
	CMS_qqzzbkg_a9.setVal(0.0769218);
	CMS_qqzzbkg_a10.setVal(98.3002);
	CMS_qqzzbkg_a11.setVal(-6.75579);
	CMS_qqzzbkg_a12.setVal(9.98691);
	CMS_qqzzbkg_a13.setVal(0.113732);
	//*/
    }
    else if (channel == 3){
   	///* 2e2mu
	CMS_qqzzbkg_a0.setVal(111.034);
	CMS_qqzzbkg_a1.setVal(8.31478);
	CMS_qqzzbkg_a2.setVal(118.605);
	CMS_qqzzbkg_a3.setVal(0.0417962);
	CMS_qqzzbkg_a4.setVal(185.498);
	CMS_qqzzbkg_a5.setVal(10.8652);
	CMS_qqzzbkg_a6.setVal(31.6752);
	CMS_qqzzbkg_a7.setVal(0.108487);
	CMS_qqzzbkg_a8.setVal(57.5729);
	CMS_qqzzbkg_a9.setVal(0.0794706);
	CMS_qqzzbkg_a10.setVal(85.5237);
	CMS_qqzzbkg_a11.setVal(-16.9261);
	CMS_qqzzbkg_a12.setVal(7167.26);
	CMS_qqzzbkg_a13.setVal(0.214606);
	//*/
    }
    else {
        std::cout << "disaster" << std::endl;
    }
    
    RooqqZZPdf_v2* bkg_qqzz = new RooqqZZPdf_v2("bkg_qqzz","bkg_qqzz",*ZZMass,
						CMS_qqzzbkg_a0,CMS_qqzzbkg_a1,CMS_qqzzbkg_a2,CMS_qqzzbkg_a3,CMS_qqzzbkg_a4,
						CMS_qqzzbkg_a5,CMS_qqzzbkg_a6,CMS_qqzzbkg_a7,CMS_qqzzbkg_a8,
						CMS_qqzzbkg_a9,CMS_qqzzbkg_a10,CMS_qqzzbkg_a11,CMS_qqzzbkg_a12,CMS_qqzzbkg_a13);
    
    /*
    CMS_qqzzbkg_a0.setConstant(kTRUE); 	CMS_qqzzbkg_a1.setConstant(kTRUE); 	CMS_qqzzbkg_a2.setConstant(kTRUE); 	CMS_qqzzbkg_a3.setConstant(kTRUE);
    CMS_qqzzbkg_a4.setConstant(kTRUE); 	CMS_qqzzbkg_a5.setConstant(kTRUE); 	CMS_qqzzbkg_a6.setConstant(kTRUE); 	CMS_qqzzbkg_a7.setConstant(kTRUE);
    CMS_qqzzbkg_a8.setConstant(kTRUE); 	CMS_qqzzbkg_a9.setConstant(kTRUE); 	CMS_qqzzbkg_a10.setConstant(kTRUE); 	CMS_qqzzbkg_a11.setConstant(kTRUE);
    CMS_qqzzbkg_a12.setConstant(kTRUE); CMS_qqzzbkg_a13.setConstant(kTRUE);
    */
    //// ---------------------------------------
	
    // commented out because all parameters are fixed
    RooFitResult *r1 = bkg_qqzz->fitTo( *set, Save(kTRUE), SumW2Error(kTRUE) );//, Save(kTRUE), SumW2Error(kTRUE)) ;
    
    std::cout << "if (channel== " << channel << "){" << std::endl;
    std::cout << "a0_bkgd = " << CMS_qqzzbkg_a0.getVal() << ";" << std::endl;
    std::cout << "a1_bkgd = " << CMS_qqzzbkg_a1.getVal() << ";" << std::endl;
    std::cout << "a2_bkgd = " << CMS_qqzzbkg_a2.getVal() << ";" << std::endl;
    std::cout << "a3_bkgd = " << CMS_qqzzbkg_a3.getVal() << ";" << std::endl;
    std::cout << "a4_bkgd = " << CMS_qqzzbkg_a4.getVal() << ";" << std::endl;
    std::cout << "a5_bkgd = " << CMS_qqzzbkg_a5.getVal() << ";" << std::endl;
    std::cout << "a6_bkgd = " << CMS_qqzzbkg_a6.getVal() << ";" << std::endl;
    std::cout << "a7_bkgd = " << CMS_qqzzbkg_a7.getVal() << ";" << std::endl;
    std::cout << "a8_bkgd = " << CMS_qqzzbkg_a8.getVal() << ";" << std::endl;
    std::cout << "a9_bkgd = " << CMS_qqzzbkg_a9.getVal() << ";" << std::endl;
    std::cout << "a10_bkgd = " << CMS_qqzzbkg_a10.getVal() << ";" << std::endl;
    std::cout << "a11_bkgd = " << CMS_qqzzbkg_a11.getVal() << ";" << std::endl;
    std::cout << "a12_bkgd = " << CMS_qqzzbkg_a12.getVal() << ";" << std::endl;
    std::cout << "a13_bkgd = " << CMS_qqzzbkg_a13.getVal() << ";" << std::endl;
    std::cout << "}" << std::endl;
    
    double qqzznorm;
    if (channel == 1) qqzznorm = 20.5836;
    else if (channel == 2) qqzznorm = 13.8871;
    else if (channel == 3) qqzznorm = 32.9883;
    else { std::cout << "disaster!" << std::endl; }

    ZZMass->setRange("fullrange",100.,1000.);
    ZZMass->setRange("largerange",100.,600.);
    ZZMass->setRange("zoomrange",100.,200.);
    
    double rescale = qqzznorm/totalweight;
    double rescale_z = qqzznorm/totalweight_z;
    std::cout << "rescale: " << rescale << ", rescale_z: " << rescale_z << std::endl;

    // Plot m4l and
    RooPlot* frameM4l = ZZMass->frame(Title("M4L"),Range(100,600),Bins(250)) ;
    set->plotOn(frameM4l, MarkerStyle(20), Rescale(rescale)) ;
  
    //set->plotOn(frameM4l) ;
    RooPlot* frameM4lz = ZZMass->frame(Title("M4L"),Range(100,200),Bins(100)) ;
    set->plotOn(frameM4lz, MarkerStyle(20), Rescale(rescale)) ;



    int iLineColor = 1;
    string lab = "blah";
    if (channel == 1) { iLineColor = 2; lab = "4#mu"; }
    if (channel == 3) { iLineColor = 4; lab = "2e2#mu"; }
    if (channel == 2) { iLineColor = 6; lab = "4e"; }

    bkg_qqzz->plotOn(frameM4l,LineColor(iLineColor),NormRange("largerange")) ;
    bkg_qqzz->plotOn(frameM4lz,LineColor(iLineColor),NormRange("zoomrange")) ;
    
    
    double normalizationBackground_qqzz = bkg_qqzz->createIntegral( RooArgSet(*ZZMass), Range("fullrange") )->getVal();
    std::cout << "Norm all = " << normalizationBackground_qqzz << std::endl;
    
    frameM4l->GetXaxis()->SetTitle("m_{4l} [GeV]");
    frameM4l->GetYaxis()->SetTitle("a.u.");
    frameM4lz->GetXaxis()->SetTitle("m_{4l} [GeV]");
    frameM4lz->GetYaxis()->SetTitle("a.u.");

    char lname[192];
    sprintf(lname,"qq #rightarrow ZZ #rightarrow %s", lab.c_str() );
    char lname2[192];
    sprintf(lname2,"Shape Model, %s", lab.c_str() );
    // dummy!
    TF1* dummyF = new TF1("dummyF","1",0.,1.);
    TH1F* dummyH = new TH1F("dummyH","",1, 0.,1.);
    dummyF->SetLineColor( iLineColor );
    dummyF->SetLineWidth( 2 );
    
    //dummyH->SetLineColor( kBlue );
    TLegend * box2 = new TLegend(0.5,0.70,0.90,0.90);
    box2->SetFillColor(0);
    box2->SetBorderSize(0);
    box2->AddEntry(dummyH,"Simulation (POWHEG+Pythia)  ","pe");
    box2->AddEntry(dummyH,lname,"");
    box2->AddEntry(dummyH,"","");
    box2->AddEntry(dummyF,lname2,"l");
    
    TPaveText *pt = new TPaveText(0.15,0.955,0.4,0.99,"NDC");
    pt->SetFillColor(0);
    pt->SetBorderSize(0);
    pt->AddText("CMS Preliminary 2012");
    TPaveText *pt2 = new TPaveText(0.84,0.955,0.99,0.99,"NDC");
    pt2->SetFillColor(0);
    pt2->SetBorderSize(0);
    pt2->AddText("#sqrt{s} = 7 TeV"); 		
        
    
    TCanvas *c = new TCanvas("c","c",800,600);
    c->cd();
    frameM4l->Draw();
    frameM4l->GetYaxis()->SetRangeUser(0,0.8);
    box2->Draw();
    pt->Draw();
    pt2->Draw();
    
    char outputName[192];
    sprintf(outputName, "bkgFigs/bkgqqzz_%s.eps",schannel.c_str());
    c->SaveAs(outputName);
    
    
    TCanvas *c2 = new TCanvas("c2","c2",1000,500);
    c2->Divide(2,1);
    c2->cd(1);
    frameM4l->Draw();
    c2->cd(2);
    frameM4lz->Draw();
    
    sprintf(outputName, "bkgFigs/bkgqqzz_%s_z.eps",schannel.c_str());
    c2->SaveAs(outputName);
    sprintf(outputName, "bkgFigs/bkgqqzz_%s_z.root",schannel.c_str());
    TFile* outF = new TFile(outputName,"RECREATE");
    outF->cd();
    c2->Write();
    frameM4l->Write();
    frameM4lz->Write();	
    outF->Close();
}

