/////////////////////////////////////////////////////////////////////////
//
// 'ORGANIZATION AND SIMULTANEOUS FITS' RooFit tutorial macro #503
// 
// Reading and using a workspace
//
// --> The input file for this macro is generated by rf502_wspaceread.C
// 
//
// 07/2008 - Wouter Verkerke 
//
/////////////////////////////////////////////////////////////////////////
/*
 #ifndef __CINT__
 #include "RooGlobalFunc.h"
 #endif
 #include "RooRealVar.h"
 #include "RooDataSet.h"
 #include "RooGaussian.h"
 #include "RooConstVar.h"
 #include "RooChebychev.h"
 #include "RooAddPdf.h"
 #include "RooWorkspace.h"
 #include "RooPlot.h"
 #include "TCanvas.h"
 #include "TAxis.h"
 #include "TFile.h"
 #include "TH1.h"
 */
using namespace RooFit ;

void backgroundFits_ggzz_1Dw(string fileName = "../../Histogramming/rootFiles_mZ12/ggZZ_2e2mu.root", int channel = 3)
{
	
	gSystem->AddIncludePath("-I$ROOFITSYS/include");
	gROOT->ProcessLine(".L ../CreateDatacards/include/tdrstyle.C");
	setTDRStyle();
	gStyle->SetPadLeftMargin(0.16);
	
	string schannel;
	if (channel == 1) schannel = "4mu";
	else if (channel == 2) schannel = "4e";
	else if (channel == 3) schannel = "2mu2e";
	else std::cout << "Not a valid channel" << std::endl;
	
	// R e a d   w o r k s p a c e   f r o m   f i l e
	// -----------------------------------------------
	
	// Open input file with workspace (generated by rf14_wspacewrite)
	char infile[192];
	sprintf(infile,"%s",fileName.c_str());
	TFile *f = new TFile(infile) ;
	char outfile[192];
	sprintf( outfile, "figs/pdf_%s_bkg.eps", schannel.c_str() );
	//f->ls();
	//RooRealVar CMS_zz4l_mass("ZZMass","ZZMass",110.,250.);
	//RooRealVar mZStar("mZStar","m'_{Z*}",10,90);
	//TCut cutString2 = "mZStar > 12";
	//RooDataSet dataT("dataT","dataT",(TTree*)f->Get("outTree"),RooArgSet(CMS_zz4l_mass,mZStar),cutString2);
	//RooDataSet set("set","set",(TTree*)f->Get("outTree"),RooArgSet(CMS_zz4l_mass));
	//RooDataSet data("data","data",(TTree*)file->Get("outTree"),mZStar);
	//RooDataSet* set = (RooDataSet*) dataT.reduce(RooArgSet(CMS_zz4l_mass)) ; 
	RooRealVar* MC_weight = new RooRealVar("scaleWeight","scaleWeight",0.,2.) ; 
	RooRealVar* ZZMass = new RooRealVar("mass2e2mu","mass2e2mu",100.,1000.);
	RooDataSet* set = new RooDataSet("set","set",(TTree*)f->Get("Ana/passedEvents"),RooArgSet(*ZZMass,*MC_weight),0,"scaleWeight");
	
        double totalweight = 0.;
	for (int i=0 ; i<set->numEntries() ; i++) { 
		set->get(i) ; 
		totalweight += set->weight();
		//cout << CMS_zz4l_mass->getVal() << " = " << set->weight() << endl ; 
	} 
	std::cout << "nEntries: " << set->numEntries() << ", totalweight: " << totalweight << std::endl;
		
	gSystem->Load("../CreateDatacards/PDFs/HZZ4LRooPdfs_cc.so");
	
	//// ---------------------------------------
	bool isLowMass = true;

	//Background
	RooRealVar CMS_qqzzbkg_a0("CMS_qqzzbkg_a0","CMS_qqzzbkg_a0",115.3,0.,200.);
	RooRealVar CMS_qqzzbkg_a1("CMS_qqzzbkg_a1","CMS_qqzzbkg_a1",21.96,0.,200.);
	RooRealVar CMS_qqzzbkg_a2("CMS_qqzzbkg_a2","CMS_qqzzbkg_a2",122.8,0.,200.);
	RooRealVar CMS_qqzzbkg_a3("CMS_qqzzbkg_a3","CMS_qqzzbkg_a3",0.03479,0.,1.);
	RooRealVar CMS_qqzzbkg_a4("CMS_qqzzbkg_a4","CMS_qqzzbkg_a4",185.5,0.,200.);
	RooRealVar CMS_qqzzbkg_a5("CMS_qqzzbkg_a5","CMS_qqzzbkg_a5",12.67,0.,200.);
	RooRealVar CMS_qqzzbkg_a6("CMS_qqzzbkg_a6","CMS_qqzzbkg_a6",34.81,0.,100.);
	RooRealVar CMS_qqzzbkg_a7("CMS_qqzzbkg_a7","CMS_qqzzbkg_a7",0.1393,0.,1.);
	RooRealVar CMS_qqzzbkg_a8("CMS_qqzzbkg_a8","CMS_qqzzbkg_a8",66.,0.,200.);
	RooRealVar CMS_qqzzbkg_a9("CMS_qqzzbkg_a9","CMS_qqzzbkg_a9",0.07191,0.,1.);
	
	RooggZZPdf_v2* bkg_ggzz = new RooggZZPdf_v2("bkg_ggzz","bkg_ggzz",*ZZMass,
						    CMS_qqzzbkg_a0,CMS_qqzzbkg_a1,CMS_qqzzbkg_a2,CMS_qqzzbkg_a3,CMS_qqzzbkg_a4,
						    CMS_qqzzbkg_a5,CMS_qqzzbkg_a6,CMS_qqzzbkg_a7,CMS_qqzzbkg_a8,CMS_qqzzbkg_a9);
	
	//// ---------------------------------------
	
	RooFitResult *r1 = bkg_ggzz->fitTo( *set, Save(kTRUE));//, SumW2Error(kTRUE) );//, Save(kTRUE), SumW2Error(kTRUE)) ;

	std::cout << "if (channel== " << channel << "){" << std::endl;
	std::cout << "a0_bkgd = " << CMS_qqzzbkg_a0.getVal() << ";" << std::endl;
	std::cout << "a1_bkgd = " << CMS_qqzzbkg_a1.getVal() << ";" << std::endl;
	std::cout << "a2_bkgd = " << CMS_qqzzbkg_a2.getVal() << ";" << std::endl;
	std::cout << "a3_bkgd = " << CMS_qqzzbkg_a3.getVal() << ";" << std::endl;
	std::cout << "a4_bkgd = " << CMS_qqzzbkg_a4.getVal() << ";" << std::endl;
	std::cout << "a5_bkgd = " << CMS_qqzzbkg_a5.getVal() << ";" << std::endl;
	std::cout << "a6_bkgd = " << CMS_qqzzbkg_a6.getVal() << ";" << std::endl;
	std::cout << "a7_bkgd = " << CMS_qqzzbkg_a7.getVal() << ";" << std::endl;
	std::cout << "a8_bkgd = " << CMS_qqzzbkg_a8.getVal() << ";" << std::endl;
	std::cout << "a9_bkgd = " << CMS_qqzzbkg_a9.getVal() << ";" << std::endl;
	std::cout << "}" << std::endl;


	int iLineColor = 1;
	string lab = "blah";
	if (channel == 1) { iLineColor = 2; lab = "4#mu"; }
	if (channel == 3) { iLineColor = 4; lab = "2e2#mu"; }
	if (channel == 2) { iLineColor = 6; lab = "4e"; }
	char lname[192];
	sprintf(lname,"gg #rightarrow ZZ #rightarrow %s", lab.c_str() );
	char lname2[192];
	sprintf(lname2,"Shape Model, %s", lab.c_str() );
	// dummy!                                                                                                                                               
	TF1* dummyF = new TF1("dummyF","1",0.,1.);
	TH1F* dummyH = new TH1F("dummyH","",1, 0.,1.);
	dummyF->SetLineColor( iLineColor );
	dummyF->SetLineWidth( 2 );

	//dummyH->SetLineColor( kBlue );                                                                                                                        
	TLegend * box2 = new TLegend(0.5,0.70,0.90,0.90);
	box2->SetFillColor(0);
	box2->SetBorderSize(0);
	box2->AddEntry(dummyH,"Simulation (GG2ZZ)  ","pe");
	box2->AddEntry(dummyH,lname,"");
	box2->AddEntry(dummyH,"","");
	box2->AddEntry(dummyF,lname2,"l");

	TPaveText *pt = new TPaveText(0.15,0.955,0.4,0.99,"NDC");
	pt->SetFillColor(0);
	pt->SetBorderSize(0);
	pt->AddText("CMS Preliminary 2012");
	TPaveText *pt2 = new TPaveText(0.84,0.955,0.99,0.99,"NDC");
	pt2->SetFillColor(0);
	pt2->SetBorderSize(0);
	pt2->AddText("#sqrt{s} = 7 TeV");


	// Plot m4l and 
	RooPlot* frameM4l = ZZMass->frame(Title("M4L"),Bins(100)) ;
	set->plotOn(frameM4l, MarkerStyle(24)) ;
	bkg_ggzz->plotOn(frameM4l,LineColor(iLineColor)) ;
	set->plotOn(frameM4l) ;

	frameM4l->GetXaxis()->SetTitle("m_{4l} [GeV]");
	frameM4l->GetYaxis()->SetTitle("a.u.");
	frameM4l->GetYaxis()->SetRangeUser(0,20);
	frameM4l->GetXaxis()->SetRangeUser(100,600);
	TCanvas *c = new TCanvas("c","c",800,600);
	c->cd();
	frameM4l->Draw();
	box2->Draw();
	pt->Draw();
	pt2->Draw();

	char outputName[192];
	sprintf(outputName, "bkgFigs/bkgggzz_%s.eps",schannel.c_str());
	c->SaveAs(outputName);
	
	
}

