/////////////////////////////////////////////////////////////////////////
//
// 'ORGANIZATION AND SIMULTANEOUS FITS' RooFit tutorial macro #503
// 
// Reading and using a workspace
//
// --> The input file for this macro is generated by rf502_wspaceread.C
// 
//
// 07/2008 - Wouter Verkerke 
//
/////////////////////////////////////////////////////////////////////////
/*
#ifndef __CINT__
#include "RooGlobalFunc.h"
#endif

#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooConstVar.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
 //*/
#include "TH1F.h"
#include "TNtuple.h"
#include "TCanvas.h"
#include <fstream>
#include <iostream>
#include <string>
#include <iomanip>
#include <sstream>
#include <algorithm>
#include "TCutG.h"
#include "TFile.h"
#include "TH2.h"
#include "TPad.h"

using namespace RooFit ;
using namespace std;
using namespace ROOT::Math;


void signalEfficiency_w(int channel = 1)
{

	gSystem->AddIncludePath("-I$ROOFITSYS/include");
	gROOT->ProcessLine(".L ~/tdrstyle.C");
	setTDRStyle();
	gStyle->SetStatX(-0.5);
	gSystem->Load("../CreateDatacards/include/HiggsCSandWidth_cc.so");
	gSystem->Load("../CreateDatacards/PDFs/HZZ4LRooPdfs_cc.so");

	string schannel;
	if (channel == 1) schannel = "4mu";
	if (channel == 2) schannel = "4e";
	if (channel == 3) schannel = "2mu2e";
	std::cout << "schannel = " << schannel << std::endl;

	const int nPoints = 17.;
	int masses[nPoints] = {120,130,140,150,160,170,180,190,200,250,300,350,400,450,500,550,600};
	double mHVal[nPoints] = {120,130,140,150,160,170,180,190,200,250,300,350,400,450,500,550,600};
	double efficiencyVal[nPoints];
	// R e a d   w o r k s p a c e   f r o m   f i l e
	// -----------------------------------------------
	
	double a_meanBW[nPoints];
	double a_gammaBW[nPoints];
	double a_meanCB[nPoints];
	double a_sigmaCB[nPoints];
	double a_alphaCB[nPoints];
	double a_nCB[nPoints];

	HiggsCSandWidth *myCSW = new HiggsCSandWidth();
	
	for (int i = 0; i < nPoints; i++){
	//for (int i = 0; i < 1; i++){
		
        /*
		double sqrts = 7.;
		double widthHVal =  myCSW->HiggsWidth(0,mHVal[i]);
		double BRHZZ;
		if (channel == 3){
			BRHZZ = myCSW->HiggsWidth(13,mHVal[i])/myCSW->HiggsWidth(15,mHVal[i]);
		}
		else{
			BRHZZ = (myCSW->HiggsWidth(14,mHVal[i])-myCSW->HiggsWidth(13,mHVal[i]))/myCSW->HiggsWidth(15,mHVal[i])/2;	
		}
		//std::cout << "0: " << myCSW->HiggsWidth(0,mHVal[i]) << std::endl;
		std::cout << "11: " << myCSW->HiggsWidth(11,mHVal[i]) << std::endl;
		std::cout << "13: " << myCSW->HiggsWidth(13,mHVal[i]) << std::endl;
		std::cout << "14: " << myCSW->HiggsWidth(14,mHVal[i]) << std::endl;
		std::cout << "15: " << myCSW->HiggsWidth(15,mHVal[i]) << std::endl;
		std::cout << "BRHZZ: " << BRHZZ << std::endl;
		*/
        
		// Open input file with workspace (generated by rf14_wspacewrite)
		char infile[192];
        sprintf(infile,"dataLM_wWeights/standard/signal/%s/ZZAnalysisTree_H%i%s.root",schannel.c_str(),masses[i],schannel.c_str());
		TFile *f = new TFile(infile) ;
		TTree *t1 = (TTree*) f->Get("SelectedTree");
        float MC_weight_norm;
		t1->SetBranchAddress("MC_weight_norm",&MC_weight_norm);
        float totalCtr=0;
        for (int a = 0; a < t1->GetEntries(); a++){ t1->GetEntry(a); totalCtr+=MC_weight_norm; }

        std::cout << "efficiency for m = " << masses[i] << " is " << totalCtr << std::endl;
        efficiencyVal[i] = totalCtr;

		/*
        int evtCount;
		std::cout << "infile: " << infile << std::endl;
		t1->SetBranchAddress("Nevt_Gen",&evtCount);
		//t1->Print();
		double eventsGen;
		for (int a = 0; a < t1->GetEntries(); a++){ t1->GetEntry(a); std::cout << " nevt: " << evtCount << std::endl; eventsGen = (double) evtCount; }
		TTree *t2 = (TTree*) f->Get("outTree");
		double eventsSelected = (double) t2->GetEntries();
		std::cout << "eventsSelected: " << eventsSelected << std::endl;
		double effCur = eventsSelected/(eventsGen*BRHZZ);
		std::cout << "effCur = " << effCur << std::endl;
		efficiencyVal[i] = effCur;
         */
        
        
		//delete *f;
		//delete *t1;
		//delete *t2;
	}
	
	TGraph* grEff = new TGraph( nPoints, mHVal, efficiencyVal );
	grEff->SetMarkerStyle(20);
	
	TF1 *polyFunc= new TF1("polyFunc","([0]+[1]*TMath::Erf( (x-[2])/[3] ))*([4]+[5]*x+[6]*x*x)", 110., 600.);
	polyFunc->SetParameters(0.10, 1.42616e-01, 100., 40.,0.6448,0.00226,-1.859e-06);
	//polyFunc1->FixParameter(0,0.10);
	polyFunc->SetLineColor(4);      
	TCanvas *c = new TCanvas("c","c",700,700);
	c->SetGrid();
	TH1F *hr = c->DrawFrame(0.,-0.1,610.,1.);
	grEff->Fit(polyFunc,"Rt");
    char xaxisText[192];
    sprintf(xaxisText,"mass (%s)", schannel.c_str());
	hr->GetXaxis()->SetTitle(xaxisText);
	char yaxisText[192];
	sprintf(yaxisText, "efficiency, %s", schannel.c_str());
	hr->GetYaxis()->SetTitle(yaxisText);
	grEff->Draw("P");

	polyFunc->Draw("sames");
    hr->Draw("AXIGSAME");

	char outname[192];
	sprintf(outname,"sigFigs/eff_%s.eps",schannel.c_str());
	c->SaveAs(outname);
	
	std::cout << "if (channel== " << channel << "){" << std::endl;
	std::cout << "p0 = " << polyFunc->GetParameter(0) << std::endl;
	std::cout << "p1 = " << polyFunc->GetParameter(1) << std::endl;
	std::cout << "p2 = " << polyFunc->GetParameter(2) << std::endl;
	std::cout << "p3 = " << polyFunc->GetParameter(3) << std::endl;
	std::cout << "p4 = " << polyFunc->GetParameter(4) << std::endl;
	std::cout << "p5 = " << polyFunc->GetParameter(5) << std::endl;
	std::cout << "p6 = " << polyFunc->GetParameter(6) << std::endl;
	std::cout << "}" << std::endl;
    
    // deviations
    std::cout << "Deviations..." << std::endl;
	for (int i = 0; i < nPoints; i++){
        double eval = polyFunc.Eval(masses[i]);
        std::cout << "For mass, " << masses[i] << ": measured value is " << efficiencyVal[i] << " and difference from function is " << (eval - efficiencyVal[i]) << std::endl;
    }
		
}
